const SAVE_USERS = `FECTH_USERS`
const SAVE_POSTS = `SAVE_POSTS`
const REQUEST_COMMENT = `REQUEST_COMMENT`
const FETCH_USERS = `FETCH_USERS`
const FETCH_POSTS = `FETCH_POSTS`
const SHOW_ERROR = `SHOW_ERRROR`
const SAVE_COMMENTS = `SAVE_COMMENTS`
const SET_CURRENT_USER = `SET_CURRENT_USER`

export {
  SAVE_USERS,
  SAVE_POSTS,
  REQUEST_COMMENT,
  FETCH_USERS,
  FETCH_POSTS,
  SHOW_ERROR,
  SAVE_COMMENTS,
  SET_CURRENT_USER,
}
